[kernel] Parsing demoadsan.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] demoadsan.c:6: allocating variable __malloc_main_l6
[eva] using specification for function strcpy
[eva:alarm] demoadsan.c:7: Warning: 
  function strcpy: precondition 'room_string' got status unknown.
[eva] FRAMAC_SHARE/libc/string.h:373: 
  cannot evaluate ACSL term, unsupported ACSL construct: logic function strcmp
[eva] using specification for function printf_va_1
[eva:alarm] demoadsan.c:8: Warning: 
  function printf_va_1: precondition valid_read_string(param0) got status unknown.
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  __fc_heap_status ∈ [--..--]
  s ∈ {{ &__malloc_main_l6[0] }}
  __retres ∈ {0}
  S___fc_stdout[0..1] ∈ [--..--]
  __malloc_main_l6[0..12] ∈ [--..--] or UNINITIALIZED
                  [13..99] ∈ UNINITIALIZED
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 5 statements reached (out of 5): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     3 valid     2 unknown     0 invalid      5 total
  60% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
