[kernel] Parsing sampleO.c (with preprocessing)
[variadic] sampleO.c:7: Warning: 
  Call to function snprintf with non-static format argument: assuming that parameters are coherent with the format, and that no %n specifiers are present in the actual string.
[variadic:typing] sampleO.c:9: Warning: 
  Incorrect type for argument 3. The argument will be cast from int to unsigned int.
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva:alarm] sampleO.c:7: Warning: 
  out of bounds read. assert \valid_read(argv + 1);
[eva] using specification for function snprintf_va_1
[eva:alarm] sampleO.c:7: Warning: 
  function snprintf_va_1: precondition valid_read_string(format) got status unknown.
[eva] using specification for function printf_va_1
[eva:alarm] sampleO.c:8: Warning: 
  function printf_va_1: precondition valid_read_string(param1) got status unknown.
[eva] using specification for function printf_va_2
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  answer ∈ {42}
  buffer[0..179] ∈ [--..--] or UNINITIALIZED
  __retres ∈ {0}
  S___fc_stdout[0].__fc_FILE_id ∈ [--..--]
               [0].__fc_FILE_data ∈
               {{ garbled mix of &{answer; buffer}
                (origin: Library function) }}
               [1] ∈ [--..--]
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 7 statements reached (out of 7): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 invalid memory access
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     3 valid     2 unknown     0 invalid      5 total
  60% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
