[kernel] Parsing sampleF.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] sampleF.c:6: allocating variable __malloc_main_l6
[eva:alarm] sampleF.c:7: Warning: 
  accessing uninitialized left-value. assert \initialized(i);
[eva:alarm] sampleF.c:7: Warning: out of bounds read. assert \valid_read(i);
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  NON TERMINATING FUNCTION
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 2 statements reached (out of 5): 40% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  2 alarms generated by the analysis:
       1 invalid memory access
       1 access to uninitialized left-values
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
