[kernel] Parsing sampleM.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] sampleM.c:16: allocating variable __malloc_main_l16
[eva] using specification for function printf_va_1
[eva] sampleM.c:19: allocating variable __malloc_main_l19
[eva] using specification for function printf_va_2
[eva] using specification for function strcpy
[eva:alarm] sampleM.c:6: Warning: 
  function strcpy: precondition 'room_string' got status unknown.
[eva] FRAMAC_SHARE/libc/string.h:373: 
  cannot evaluate ACSL term, unsupported ACSL construct: logic function strcmp
[eva:alarm] sampleM.c:22: Warning: 
  accessing left-value that contains escaping addresses.
  assert ¬\dangling(&a);
[eva:alarm] sampleM.c:22: Warning: 
  function strcpy: precondition 'room_string' got status unknown.
[eva] using specification for function puts
[eva:alarm] sampleM.c:10: Warning: 
  function puts: precondition 'valid_string_s' got status unknown.
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function do_stuff:
  S___fc_stdout[0].__fc_FILE_id ∈
               {{ garbled mix of &{__malloc_main_l16; __malloc_main_l19}
                (origin: Misaligned {sampleM.c:10}) }}
               [0].__fc_FILE_data ∈
               {{ garbled mix of &{__malloc_main_l16; __malloc_main_l19}
                (origin: Misaligned {sampleM.c:10}) }} or ESCAPINGADDR
               [1] ∈ [--..--]
[eva:final-states] Values at end of function init:
  __malloc_main_l19[0..7] ∈ [--..--] or UNINITIALIZED
                   [8..9] ∈ UNINITIALIZED
[eva:final-states] Values at end of function main:
  __fc_heap_status ∈ [--..--]
  a ∈ {{ (void *)&__malloc_main_l16 }}
  b ∈ ESCAPINGADDR
  __retres ∈ {0}
  S___fc_stdout[0] ∈
               {{ garbled mix of &{__malloc_main_l16}
                (origin: Misaligned {sampleM.c:10}) }} or ESCAPINGADDR
               [1] ∈ [--..--]
  __malloc_main_l16[0..8] ∈ [--..--] or UNINITIALIZED
                   [9] ∈ UNINITIALIZED
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  3 functions analyzed (out of 3): 100% coverage.
  In these functions, 15 statements reached (out of 15): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 escaping address
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     8 valid     3 unknown     0 invalid     11 total
  72% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
