[kernel] Parsing sampleA.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] sampleA.c:5: allocating variable __malloc_main_l5
[eva:alarm] sampleA.c:9: Warning: 
  accessing left-value that contains escaping addresses.
  assert ¬\dangling(&p);
[kernel] sampleA.c:9: Warning: 
  all target addresses were invalid. This path is assumed to be dead.
[eva] done for function main
[eva] sampleA.c:9: assertion 'Eva,dangling_pointer' got final status invalid.
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  __fc_heap_status ∈ [--..--]
  p ∈ {0}
  __retres ∈ {0}
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 6 statements reached (out of 6): 100% coverage.
  ----------------------------------------------------------------------------
  Some errors and warnings have been raised during the analysis:
    by the Eva analyzer:      0 errors    0 warnings
    by the Frama-C kernel:    0 errors    1 warning
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 escaping address
  1 of them is a sure alarm (invalid status).
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     1 valid     0 unknown     0 invalid      1 total
  100% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
