[kernel] Parsing sampleN.c (with preprocessing)
[variadic:typing] sampleN.c:10: Warning: 
  Incorrect type for argument 3. The argument will be cast from int to unsigned int.
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] using specification for function printf_va_1
[eva] using specification for function printf_va_2
[eva] FRAMAC_SHARE/libc/stdio.h:317: 
  Cannot evaluate range bound gets_length{Old}
  (unsupported ACSL construct: logic function gets_length). Approximating
[eva] using specification for function gets
[eva] FRAMAC_SHARE/libc/stdio.h:316: 
  Cannot evaluate range bound gets_length
  (unsupported ACSL construct: logic function gets_length). Approximating
[eva:alarm] sampleN.c:8: Warning: 
  function gets: precondition 'room_s' got status unknown.
[eva] using specification for function printf_va_3
[eva:alarm] sampleN.c:9: Warning: 
  function printf_va_3: precondition valid_read_string(param1) got status unknown.
[eva] using specification for function printf_va_4
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  answer ∈ {42}
  buffer[0..39] ∈ [--..--] or UNINITIALIZED
  __retres ∈ {0}
  S___fc_stdin[0..1] ∈ [--..--]
  S___fc_stdout[0].__fc_FILE_id ∈ [--..--]
               [0].__fc_FILE_data ∈
               {{ garbled mix of &{answer; buffer}
                (origin: Library function) }}
               [1] ∈ [--..--]
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 8 statements reached (out of 8): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     4 valid     2 unknown     0 invalid      6 total
  66% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
