[kernel] Parsing sampleP.c (with preprocessing)
[variadic:typing] sampleP.c:10: Warning: 
  Incorrect type for argument 3. The argument will be cast from int to unsigned int.
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] using specification for function printf_va_1
[eva:alarm] sampleP.c:8: Warning: 
  out of bounds read. assert \valid_read(argv + 1);
[eva] using specification for function strcpy
[eva:alarm] sampleP.c:8: Warning: 
  function strcpy: precondition 'valid_string_src' got status unknown.
[eva:alarm] sampleP.c:8: Warning: 
  function strcpy: precondition 'room_string' got status unknown.
[eva] FRAMAC_SHARE/libc/string.h:373: 
  cannot evaluate ACSL term, unsupported ACSL construct: logic function strcmp
[eva] using specification for function printf_va_2
[eva:alarm] sampleP.c:9: Warning: 
  function printf_va_2: precondition valid_read_string(param1) got status unknown.
[eva] using specification for function printf_va_3
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  answer ∈ {42}
  buffer[0..39] ∈ [--..--] or UNINITIALIZED
  __retres ∈ {0}
  S___fc_stdout[0].__fc_FILE_id ∈ [--..--]
               [0].__fc_FILE_data ∈
               {{ garbled mix of &{answer; buffer}
                (origin: Library function) }}
               [1] ∈ [--..--]
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 8 statements reached (out of 8): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 invalid memory access
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions     4 valid     3 unknown     0 invalid      7 total
  57% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
