[kernel] Parsing sampleL.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] sampleL.c:13: allocating variable __malloc_main_l13
[eva] using specification for function printf_va_1
[eva] sampleL.c:15: allocating variable __malloc_main_l15
[eva] using specification for function printf_va_2
[eva:alarm] sampleL.c:20: Warning: 
  accessing left-value that contains escaping addresses.
  assert ¬\dangling(&a);
[eva] sampleL.c:22: allocating variable __malloc_main_l22
[eva] using specification for function printf_va_3
[eva] sampleL.c:24: allocating variable __malloc_main_l24
[eva] using specification for function printf_va_4
[eva] sampleL.c:26: allocating variable __malloc_main_l26
[eva] using specification for function printf_va_5
[eva] using specification for function strcpy
[eva:alarm] sampleL.c:29: Warning: 
  function strcpy: precondition 'room_string' got status unknown.
[eva] FRAMAC_SHARE/libc/string.h:373: 
  cannot evaluate ACSL term, unsupported ACSL construct: logic function strcmp
[eva] using specification for function puts
[eva:alarm] sampleL.c:30: Warning: 
  function puts: precondition 'valid_string_s' got status invalid.
[eva] done for function main
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  NON TERMINATING FUNCTION
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 16 statements reached (out of 18): 88% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 escaping address
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     0 invalid      0 total
    Preconditions    10 valid     1 unknown     1 invalid     12 total
  83% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
