[kernel] Parsing sampleB.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva] Computing initial state
[eva] Initial state computed
[eva:initial-state] Values of globals at initialization
  
[eva] sampleB.c:5: allocating variable __malloc_main_l5
[eva:alarm] sampleB.c:8: Warning: out of bounds write. assert \valid(p + 3);
[kernel] sampleB.c:8: Warning: 
  all target addresses were invalid. This path is assumed to be dead.
[eva] done for function main
[eva] sampleB.c:8: assertion 'Eva,mem_access' got final status invalid.
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  __fc_heap_status ∈ [--..--]
  p ∈ {0}
  __retres ∈ {0}
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 5 statements reached (out of 6): 83% coverage.
  ----------------------------------------------------------------------------
  Some errors and warnings have been raised during the analysis:
    by the Eva analyzer:      0 errors    0 warnings
    by the Frama-C kernel:    0 errors    1 warning
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 invalid memory access
  1 of them is a sure alarm (invalid status).
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
